### PR TITLE
Make logview cache-filename customizable

### PR DESCRIPTION
**Pull request by dakra**

### CODE REVIEW

**Comment by doublep** [comment]
What would be the reason to customize this variable?

**Comment by dakra** [comment]
Same reason why someone wants to configure the logview.views variable. I use the `no-litter` package and have my config relevant stuff in etc and temp/cache files under var. Logview ist the only package that litters my Emacs home dir with no way of configuring it.

Thanks for the package btw.

**Comment by dakra** [comment]
> Is there a way Logview could find a good place for its cache file automatically?

Hmm, I can make a `(featurep 'no-littering)` to check if [no-littering](https://github.com/emacscollective/no-littering) is installed and put it in the right directory if it is and under `.emacs` otherwise?

> I'm not fond of creating tons of customization options since that makes it harder to notice more useful ones.

I can change it to `defvar` if you're worried about cluttering the customization interface.
Even if we do the feature detection above I would make it a variable so someone can
customize it if they want to.

**Comment by doublep** [comment]
Hm, looking at that 'no-littering' library... Apparently, it changes customizable variable values in other packages. But, on the other hand, the source is not that large and last commit is 5 month ago.

I don't know what to do.

* Just apply your change and let filenames be customizable (including by 'no-littering')?
* Make Logview try to put files in `etc`/`var` as appropriate if 'no-littering' is installed?

What is better? 'no-littering' doesn't seem to include clear instructions for other packages.

**Comment by dakra** [comment]
Not sure if it helps but as a datapoint I looked at my installed packages (over 250) and only 1 uses `(featurep 'no-littering)` (hacker-typer) and one uses always `etc`/`var` no matter if no-littering is installed or not (prescient). Also both are customizable of course.

So I would say just making it customizable and putting it in `user-emacs-directory` seems to be the most used option.
Maybe we can ping @tarsius and ask if there is a recommendation from no-littering what package authors should do.

**Comment by doublep** [comment]
I merged your changes, just changed the comment for the new variable.

**Pull request merged**
